Provide Argon2id overloads to pass password hashes as strings
samuel-lucas6/Geralt pull request #15
Opened 2024-12-11 19:07 UTC by ektrah

It can be a bit tricky to convert the password hash correctly between `Span<byte>` and `string`, so it might be helpful to provide overloads in the `Argon2id` class that do the conversion for the user.

The unsafe code can be replaced with `Marshal.AllocHGlobal`, `Marshal.Marshal.PtrToStringAnsi`, and `Marshal.FreeHGlobal` in a `try ... finally ...` if preferred.

2024-12-11 21:29 UTC, samuel-lucas6 commented
This is a good idea. Thanks @ektrah! I'll try to take a look tomorrow if I get time.

2024-12-12 21:29 UTC, samuel-lucas6 requested changes
Right, I've taken a look. I'm happy to do these changes myself if you'd prefer. I don't really know what the etiquette is with PRs.

2024-12-12 21:29 UTC, samuel-lucas6 commented on src/Geralt/Crypto/Argon2id.cs
> +        unsafe
Please could you change this to an unsafe method.

2024-12-12 21:29 UTC, samuel-lucas6 commented on src/Geralt/Crypto/Argon2id.cs
> +        Validation.NotNull(nameof(hash), hash);
Please change this to `Validation.NotNullOrEmpty()`.

2024-12-12 21:29 UTC, samuel-lucas6 commented on src/Geralt/Crypto/Argon2id.cs
> +        Validation.NotNull(nameof(hash), hash);
Please change this to `Validation.NotNullOrEmpty()`.

2024-12-12 21:29 UTC, samuel-lucas6 commented on src/Geralt/Crypto/Argon2id.cs
> +        {
Please put the first bracket on the same line as the `if`.

2024-12-12 21:29 UTC, samuel-lucas6 commented on src/Geralt/Crypto/Argon2id.cs
> +        Validation.NotNull(nameof(hash), hash);
Actually, it's probably better to do `Validation.NotNull()` and then `Validation.SizeBetween()` with the `MinHashSize` and `MaxHashSize` constants.

2024-12-12 21:29 UTC, samuel-lucas6 commented on src/Geralt/Crypto/Argon2id.cs
> +        Validation.NotNull(nameof(hash), hash);
Again, it's probably better to do `Validation.NotNull()` and then `Validation.SizeBetween()` with the `MinHashSize` and `MaxHashSize` constants.

2024-12-12 21:29 UTC, samuel-lucas6 commented on src/Geralt/Crypto/Argon2id.cs
> +            sbyte* hash = stackalloc sbyte[crypto_pwhash_STRBYTES];
This could be changed to `MaxHashSize`.

2024-12-12 21:29 UTC, samuel-lucas6 commented on src/Geralt.Tests/Argon2idTests.cs
> +
Missing `ComputeHash_String_Invalid`, not that there's much to test.

2024-12-12 21:29 UTC, samuel-lucas6 commented on src/Geralt.Tests/Argon2idTests.cs
> +    public void ComputeHash_Valid_String(string password, int iterations, int memorySize)
I'd move the `_String` to before the `_Valid` in all of these.

2024-12-12 21:29 UTC, samuel-lucas6 commented on src/Geralt.Tests/Argon2idTests.cs
> +        Assert.IsFalse(Argon2id.VerifyHash(hash, p));
I'd split this into two lines with a space.

2024-12-12 21:29 UTC, samuel-lucas6 commented on src/Geralt.Tests/Argon2idTests.cs
> +
There are also no `NeedsRehash` tests.

2024-12-22 09:50 UTC, samuel-lucas6 commented
Thank you for making changes. I'll try to review this next weekend.

2024-12-29 12:00 UTC, samuel-lucas6 approved these changes
I'll address the remaining comments.

2024-12-29 12:01 UTC, merged

2025-01-01 15:34 UTC, ektrah commented
The PR etiquette depends. If someone really wants their code merged into your project, you can expect them to put in some effort to make sure the code style is followed, full unit tests are included, etc.

In this case, I just wanted to make a suggestion, but not without providing some sample code to show what I mean. It's up to you whether you like the suggestion or not, and if so, whether you want to build on the sample code or implement the suggestion in a different way, which of course means some effort on your part.

I'm glad you liked my suggestion. 😸  I would perhaps even deprecate the old overloads, since there isn't much saved when passing a buffer instead of a string and the API would be come simpler. I guess  most API users will use the string overloads.

For `VerifyHash`, I'm not sure whether the method should throw an exception or return false if the hash is invalid. In general, a method should throw an exception when it is used incorrectly, and not when it is used correctly but has a negative result. If it is a wrong use of `VerifyHash` to pass an invalid hash, then it would be helpful to offer a method `ValidateHash` with which the caller of `VerifyHash` can check beforehand whether the hash is valid or not to avoid the exception.

2025-01-01 19:23 UTC, samuel-lucas6 commented
> I'm glad you liked my suggestion. 😸 I would perhaps even deprecate the old overloads, since there isn't much saved when passing a buffer instead of a string and the API would be come simpler. I guess most API users will use the string overloads.

Yes, I might do that. There's probably not much use for them.

> For VerifyHash, I'm not sure whether the method should throw an exception or return false if the hash is invalid. In general, a method should throw an exception when it is used incorrectly, and not when it is used correctly but has a negative result. If it is a wrong use of VerifyHash to pass an invalid hash, then it would be helpful to offer a method ValidateHash with which the caller of VerifyHash can check beforehand whether the hash is valid or not to avoid the exception.

This is an interesting point. However, I did it this way to prevent Argon2i hashes being verified since this library deliberately only supports Argon2id. As long as someone is using this library for computing the hashes, the method shouldn't throw.